FROM mini/ansible:2.4

ARG WORKDIR=/usr/yunji/cloudiac
WORKDIR ${WORKDIR}
USER root

RUN apk add --update git bash curl

ENV TERRASCAN_VERSION=1.9.0
RUN mkdir -p /root/.terrascan/pkg/policies/opa/rego && \
    curl -L https://github.com/accurics/terrascan/releases/download/v${TERRASCAN_VERSION}/terrascan_${TERRASCAN_VERSION}_Linux_x86_64.tar.gz | tar -xz terrascan && install terrascan /usr/local/bin && rm terrascan

RUN git clone --depth 1 https://github.com/tfutils/tfenv.git /root/.tfenv
ENV PATH="/root/.tfenv/bin:${PATH}"
RUN tfenv install "1.15.6" && \
    tfenv use "1.15.6"

COPY assets/providers /cloudiac/assets/plugins
