---
- name: 安装 Nginx
  yum:
    name: nginx
    state: present

- name: 部署 Nginx 配置
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: reload nginx

- name: 启动 Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

# - name: 确保网站根目录存在
#   file:
#     path: /var/www/html
#     state: directory
#     mode: '0755'

# - name: 部署默认首页
#   copy:
#     content: "<h1>Hello from IaC!</h1>"
#     dest: /var/www/html/index.html

- name: 验证 Nginx 运行
  uri:
    url: http://localhost/
    status_code: 200